name: 'pace_accelerator'
version: '1.0.0'
config-version: 2

profile: 'pace_accelerator'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:

  pace_accelerator:

    bronze:
      +materialized: view
      +schema: bronze

    silver:
      +materialized: table
      +schema: silver

    gold:
      +materialized: table
      +schema: gold

snapshots:
  pace_accelerator:
    +target_schema: snapshots

seeds:
  pace_accelerator:
    +schema: bronze

vars:
  project_name: "PACE Accelerator"
  owner: "Deepika"
  environment: "DEV"

quoting:
  database: false
  schema: false
  identifier: false