PACE_operations:
  target: dev

  outputs:

    dev:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"

      role: PACE_ROLE_DBT_TRANSFORM_DEV
      database: DEV_PACE_DW
      warehouse: DEV_PACE_TRANSFORM_WH
      schema: DEV

      threads: 2
      client_session_keep_alive: false
      connect_retries: 1
      connect_timeout: 15
      retry_on_database_errors: false

    stg:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"

      role: PACE_ROLE_DBT_TRANSFORM_STG
      database: STG_PACE_DW
      warehouse: STG_PACE_TRANSFORM_WH
      schema: DBT_DEEPIKA

      threads: 2
      client_session_keep_alive: false
      connect_retries: 1
      connect_timeout: 15
      retry_on_database_errors: false

    prod:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"

      role: PACE_ROLE_DBT_TRANSFORM_PROD
      database: PROD_PACE_DW
      warehouse: PROD_PACE_TRANSFORM_WH
      schema: PROD

      
      threads: 2
      client_session_keep_alive: false
      connect_retries: 1
      connect_timeout: 15
      retry_on_database_errors: false