PACE_operations:
  target: dev

  outputs:

    dev:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('DEV_DBT_ROLE') }}"
      database: "{{ env_var('DEV_DBT_DATABASE') }}"
      warehouse: "{{ env_var('DEV_DBT_WAREHOUSE') }}"
      schema: DEV
      threads: 2
      connect_retries: 1
      retry_on_database_errors: false


    staging:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('STG_DBT_ROLE') }}"   
      database: "{{ env_var('STG_DBT_DATABASE') }}"
      warehouse: "{{ env_var('STG_DBT_WAREHOUSE') }}"
      schema: DBT_DEEPIKA
      threads: 2
      connect_retries: 1
      retry_on_database_errors: false

    prod:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('PROD_DBT_ROLE') }}"
      database: "{{ env_var('PROD_DBT_DATABASE') }}"
      warehouse: "{{ env_var('PROD_DBT_WAREHOUSE') }}"
      schema: DBT_PROD
      threads: 2
      connect_retries: 1
      retry_on_database_errors: false
