name: PACE_operations_medallion
version: '1.0.0'
config-version: 2

profile: PACE_operations

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

# ============================================================
# GLOBAL DEFAULTS
# ============================================================

models:
  PACE_operations_medallion:
    +persist_docs:
      relation: true
      columns: true

    # ================= SILVER LAYER =================

    pace_enterprise_silver_dbt_models:

      +materialized: table

      enterprise_silver_participant:
        +schema: SILVER_PARTICIPANT

      enterprise_silver_provider:
        +schema: SILVER_PROVIDER

      enterprise_silver_appointment:
        +schema: SILVER_APPOINTMENT

      enterprise_silver_caregiver:
        +schema: SILVER_CAREGIVER

      enterprise_silver_idt_clinical:
        +schema: SILVER_IDT_CLINICAL

      enterprise_silver_meal_delivery:
        +schema: SILVER_MEAL_DELIVERY

      enterprise_silver_transportation:
        +schema: SILVER_TRANSPORTATION

