name: 'PACE_operations'
version: '1.0.0'
config-version: 2

profile: 'PACE_operations'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"
<<<<<<< HEAD

models:
  +materialized: table   # default for all models

  silver:
    +schema: SILVER

  gold:
    +schema: GOLD

snapshots:
  +target_schema: SNAPSHOTS
=======
>>>>>>> c927a1bca1f2a513097e5461ec3f866509040752
