name: dbt CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

  release:
    types: [ created ]

jobs:

  dbt-dev:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run dbt (dev)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/usr/app \
            -e DBT_ACCOUNT=${{ secrets.DBT_ACCOUNT }} \
            -e DBT_USER=${{ secrets.DBT_USER }} \
            -e DBT_PASSWORD=${{ secrets.DBT_PASSWORD }} \
            -e DBT_ROLE=${{ secrets.DBT_ROLE }} \
            -e DBT_WAREHOUSE=${{ secrets.DBT_DEV_WAREHOUSE }} \
            -e DBT_DATABASE=${{ secrets.DBT_DEV_DATABASE }} \
            ghcr.io/dbt-labs/dbt-snowflake:1.9.latest \
            dbt build --project-dir /usr/app/PACE_operations_medallion --target dev

  dbt-staging:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run dbt (staging)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/usr/app \
            -e DBT_ACCOUNT=${{ secrets.DBT_ACCOUNT }} \
            -e DBT_USER=${{ secrets.DBT_USER }} \
            -e DBT_PASSWORD=${{ secrets.DBT_PASSWORD }} \
            -e DBT_ROLE=${{ secrets.DBT_ROLE }} \
            -e DBT_WAREHOUSE=${{ secrets.DBT_STG_WAREHOUSE }} \
            -e DBT_DATABASE=${{ secrets.DBT_STG_DATABASE }} \
            ghcr.io/dbt-labs/dbt-snowflake:1.9.latest \
            dbt build --project-dir /usr/app/PACE_operations_medallion --target staging

  dbt-prod:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run dbt (prod)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/usr/app \
            -e DBT_ACCOUNT=${{ secrets.DBT_ACCOUNT }} \
            -e DBT_USER=${{ secrets.DBT_USER }} \
            -e DBT_PASSWORD=${{ secrets.DBT_PASSWORD }} \
            -e DBT_ROLE=${{ secrets.DBT_ROLE }} \
            -e DBT_WAREHOUSE=${{ secrets.DBT_PROD_WAREHOUSE }} \
            -e DBT_DATABASE=${{ secrets.DBT_PROD_DATABASE }} \
            ghcr.io/dbt-labs/dbt-snowflake:1.9.latest \
            dbt build --project-dir /usr/app/PACE_operations_medallion --target prod
